name: 【Docker】 Build homebox
on:
  schedule:
    - cron: '0 16 * * *'
  push:
    paths: [ "homebox/Dockerfile",".github/workflows/build_homebox.yml" ]
  pull_request:
    paths: [ "homebox/Dockerfile",".github/workflows/build_homebox.yml" ]
  workflow_dispatch: ~

jobs:
  Build_Docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Get homebox version
      id: get_version
      run: |
        URL=https://api.github.com/repos/XGHeaven/homebox/releases/latest
        echo "version=$(curl -s ${URL} | grep tag_name | head -n 1 | awk -F '"' '{print $4}'| sed 's#v##')" >> $GITHUB_OUTPUT
        
    - name: Cache Docker layers
      uses: actions/cache@v4.2.1
      with:
        path: /tmp/.buildx-cache
        key: homebox-${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          homebox-${{ runner.os }}-buildx-
          
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/homebox
        tags: |
          type=raw,value=${{ steps.get_version.outputs.version }},enable=true
          type=raw,value=latest,enable=true
        labels: |
          org.opencontainers.image.author=KIMI360
          org.opencontainers.image.description=A Toolbox for Home Local Networks.
          org.opencontainers.image.licenses=MIT
          org.opencontainers.image.source=https://github.com/XGHeaven/homebox
          org.opencontainers.image.title=${{ secrets.DOCKER_USERNAME }}/homebox
          org.opencontainers.image.url=https://github.com/kimi360/Dockerfiles
          org.opencontainers.image.version=${{ steps.get_version.outputs.version }}
          org.opencontainers.image.docker.cmd=docker run -p 80:3300 -d kimi360/homebox:latest
        flavor: latest=false     

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./homebox/
        build-args: HOMEBOX_VERSION=${{ steps.get_version.outputs.version }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: |
            linux/386
            linux/amd64
            linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
